coverage:
  # Commit status https://docs.codecov.io/docs/commit-status are used
  # to block PR based on coverage threshold.
  status:
    project:
      default:
        target: auto
        threshold: 0%
    patch:
      default:
        informational: true

comment:
  behavior: default
  after_n_builds: 1
ignore:
  # Configure what to ignore.
  - "assets"
  - ".github"
  - "charts"
  - "docs"
  - "test"
  - "third_party"
codecov:
  notify:
    after_n_builds: 1
    wait_for_ci: yes